#
# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/p6200/extract_files

PRODUCT_COPY_FILES += \
    vendor/samsung/t869/props/sbin/cbd:root/sbin/cbd \
    vendor/samsung/t869/props/system/bin/gpsd:system/bin/gpsd \
    vendor/samsung/t869/props/system/lib/hw/sensors.exynos4.so:system/lib/hw/sensors.exynos4.so \
    vendor/samsung/t869/props/system/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/t869/props/system/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/t869/props/system/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/t869/props/system/lib/libsec-ril.so:system/lib/libsec-ril.so

